sudo: false # don't need root access on Travis-CI (builds faster without sudo!)

language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

os: # test on *both* Linux and OSX to ensure compatibility
  - linux
  - osx # if your project does not *need* OSX compatibility, remove this line.

env:
  - ELM_VERSION=0.18.0

cache:
  directories: # so subsequent builds run faster
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts # elm-test init creates a "tests/" dir
    - tests/elm-stuff/packages
    - sysconfcpus
    - node_modules # NPM packages

before_install:
  - uname -a       # print the *exact* operating system/kernel version
  - node --version # print Node.js version in Travis build log
  - npm --version  # print npm version in Travis build log
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then brew update; brew install nvm; mkdir ~/.nvm; export NVM_DIR=~/.nvm; source $(brew --prefix nvm)/nvm.sh;
    fi
  - | # epic build time improvement - 10 mins >> 5 sec! see https://git.io/vQcqz
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install: # install specific versions of elm & elm-test
  - npm install -g elm@$ELM_VERSION elm-test@0.18.12 elm-format@exp
  # the next 3 lines are courtesy of @rtfeldman https://git.io/vbj0j
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - echo "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - elm package install --yes # install main project dependencies
  # - cd tests                  # change into /test directory to install more deps
  # - elm package install --yes # install test dependencies
  # - cd ..                     # change back into root project directory
  - pwd

# before_script:     # print some useful debug info


script:
  # - elm-format --validate PhotoGroove.elm # lint / format-check main file
  # - elm-make PhotoGroove.elm --output elm.js --warn # attempt elm-make
  - elm-test --verbose                    # run the tests!
