sudo: false

language: node_js # elm is installed from npm (see install below)
node_js: node # use "latest" version of Node.js

os: # test on *both* linux and OSX to ensure compatibility
  - linux
  - osx

cache:
  directories: # so subsequent builds run faster
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - test/elm-stuff/build-artifacts
    - test/elm-stuff/packages
    - sysconfcpus

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then brew update; brew install nvm; mkdir ~/.nvm; export NVM_DIR=~/.nvm; source $(brew --prefix nvm)/nvm.sh;
    fi
  - | # epic build time improvement - 10 mins >> 5 sec! see https://git.io/vQcqz
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@0.18.0 elm-test@0.18.12 elm-format@exp
  - elm package install --yes

script:
  - node --version # print Node.js version in Travis Log for debugging
  - npm --version  # print npm version in Travis Log for debugging.
  - elm-test
